// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace restaurant.com
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	/// <summary>
	/// Блюдо
	/// </summary>
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class Dish : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Dish\",\"doc\":\"Блюдо\",\"namespace\":\"restaurant.com\",\"fields" +
				"\":[{\"name\":\"DishName\",\"type\":\"string\"},{\"name\":\"DishCost\",\"type\":{\"type\":\"bytes\"" +
				",\"logicalType\":\"decimal\",\"precision\":16,\"scale\":2}}]}");
		private string _DishName;
		private Avro.AvroDecimal _DishCost;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Dish._SCHEMA;
			}
		}
		public string DishName
		{
			get
			{
				return this._DishName;
			}
			set
			{
				this._DishName = value;
			}
		}
		public Avro.AvroDecimal DishCost
		{
			get
			{
				return this._DishCost;
			}
			set
			{
				this._DishCost = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DishName;
			case 1: return this.DishCost;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DishName = (System.String)fieldValue; break;
			case 1: this.DishCost = (Avro.AvroDecimal)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
